version: 0.2

phases:
  install:
    runtime-versions:
      node: 14
    commands:
      - yarn install
  test:
    commands:
      - yarn test

reports:
  test-report:
    files:
      - "./frontend/results.xml"
    file-format: "JUNITXML"