version: 0.2

phases:
  build:
    commands:
      - docker build -t autotests .
      - docker run autotests yarn test

reports:
  test-report:
    files:
      - "./frontend/results.xml"
    file-format: "JUNITXML"