version: 0.2

phases:
  build:
    commands:
      - docker build -t autotests .
  post_build:
    commands:
      - docker run --name pw-tests autotests:latest yarn test
      - docker cp pw-tests:/automation/frontend/results.xml ./results.xml

reports:
  test-report:
    files:
      - "./results.xml"
    file-format: "JUNITXML"