name: Tests with Docker

on: 
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
      tags:
        description: 'Test scenario tags'

jobs:
  test:
    runs-on: ubuntu-latest
    container: mylorii/yarn-workspaces-dockerhub
    steps:
      - run: echo "Running mylorii/yarn-workspaces-dockerhub"

      - uses: actions/checkout@v3

      - uses: actions/cache@v3
        id: cache
        with:
          path: node_modules/
          key: ${{ runner.os }}-${{ hashFiles('yarn.lock') }}

      - run: yarn test
      - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: playwright-report
        path: frontend/playwright-report/
        retention-days: 30